### ISSUE TITLE
Move Item Sets & Items Up and Down on the Lists

### ISSUE THREAD

**Issue by Cyrcle** [thommcgrath/Beacon-For-Ark#3]
From my understanding, the way the beacons determine loot is based on the order of the item sets/items and their weight.  A well explained example is [located here](https://survivetheark.com/index.php?/forums/topic/65930-tutorial-modify-loot-crate-contents-v242/) under Example Loot Crate 2.

Essentially, the order of the item sets and items matter so having the option to move items up and down the list would be a nice feature.

Another thing is that the items within the item sets, need to be properly weighted when exporting the config.  The way it is currently set up, is each item adds up to a "100% chance" of drops, but that's not how the system works from my understanding.

Just a few QoL suggestions, as this already helps so much by not having to stare at lines and lines of code.  Keep up the great work.  :+1:

**Comment by thommcgrath** [comment]
The weight I believe I have correct. It does at up to 100%. If you have two items with the same weight value, they essentially each have a 50% chance to be selected.

As for the order, I've read that forum post many times. I haven't seen anything to suggest order matters. If it did, weight would be much less important. If you can point me to something specific that leads you to believe this, I'm happy to listen. I want this as good as I can get it.

**Comment by Cyrcle** [comment]
I would have to further test it to confirm, but the way the forum post suggests is that it goes down the list of items and the weight is the chance that item is selected.  I will post back with results.

**Comment by thommcgrath** [comment]
No, actually, you are right:

> As you can see, the first entry (Stone) has a chance of 90% to be in the loot crate. So in 9 out of 10 supply drops you will get stone. If stone is in the crate, it will go to the next item: Thatch. As Thatch has a 100% chance to be in, it will be chosen as next item. Now, we have alreay reached the 2 items max. qty limit. Therefor the set's chosen items are decided now.

So I'll have to adjust how this works.

**Comment by thommcgrath** [comment]
So... I'm not convinced the source forum post is correct. I've been playing on my server with a config built by Beacon. If what this post says is correct, I should only be seeing the first items in my sets. But I'm not. We just opened a beacon an hour ago with 100 Absorbent Substrate. This is at the very bottom of the "Raw Materials" preset, which has a lot of entries. If every entry is given a 100% chance and selected in order, I should only ever see Wood, Stone, Metal, and Hide from that preset. But I don't. We've seen most items in that list.

My experience tells me this is working as intended how it's currently coded. I'm going to leave this issue open, because it's definitely worth discussion and testing.
